### ISSUE TITLE
Support for multiple drivers for Mysql, Postgres, etc.

### ISSUE THREAD

**Issue by tjheeta** [elixir-lang/ecto#635]
Use case:
Did some benchmarks and found that Mariaex was acting slowly and then made a wrapper around an erlang library that works faster. The new driver is at http://github.com/tjheeta/mysqlex.  I would like to be able to conditionally load whatever driver is available.

#636 is a potential PR, but it doesn't work correctly. Not sure what the best route is to do the conditional include. Ideas?

**Comment by josevalim** [comment]
@tjheeta can't mariaex be improved? Have you pinged its authors?

**Comment by josevalim** [comment]
I found your blog post: http://tjheeta.github.io/2015/05/31/elixir-and-erlang-mysql-drivers.html

It would be nice to identify the difference in performance. It seems we have a bunch of room for optimization in our adapters.

**Comment by josevalim** [comment]
Can you make the apps with those different drivers online? I would love to make things faster. /cc @liveforeverx

Meanwhile, I will think how to best tackle multiple drivers here.

**Comment by josevalim** [comment]
Those blog posts are very nice. :D Btw, most of the reason of the slow down in Ecto, if you are using directly the `Ecto.Adapters.SQL` is likely the cost of the pool.

**Comment by tjheeta** [comment]
The benchmarking code is at https://github.com/tjheeta/elixir_database_driver_benchmark .

I'll see if I have time to profile it. It's not apparent to me that it would be the pool since I pooled both postgrex and mysqlex. 

What would be the best way to conditionally load the drivers?

**Comment by tjheeta** [comment]
Made an issue at https://github.com/xerions/mariaex/issues/53 for the Mariaex performance.

**Comment by fishcakez** [comment]
@tjheeta please can you fix your mix.lock file in your benchmark repo so that ecto points to a valid commit so can run the same code as you.

**Comment by josevalim** [comment]
Thanks for the repo! One last question, were you running in prod
environment?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by tjheeta** [comment]
@fishcakez - just updated the repo to point ecto to 12.0-rc . To use ecto with mysqlex, you'll have to patch it with https://gist.github.com/tjheeta/800deab2b9e7b2b9651b

Apologies in advance, the ip's for the db are hardcoded in there.

**Comment by tjheeta** [comment]
Hmmm...I did not set ```MIX_ENV=prod``` on the runs. Logging is set to ```config :logger, level: :error```. 

It seems to have bumped the performance 3-5%. My setup is that finely tuned, but it does make a slight difference.

**Comment by josevalim** [comment]
Excellent. I will start benchmarking soon too!

**Comment by liveforeverx** [comment]
Thanks for doing benchmark. I'll check it.

**Comment by josevalim** [comment]
Hello @tjheeta! So Postgrex is using the extended query, which is the preferred and safest way to send queries with Postgres and epgsql is using the simple query.

Simple query is quite limited, it does not support some types nor query parameters. So text is beneficial for very simple and small queries but it becomes much slower for bigger data.

In any case, if both postgrex and epgsql use extended, their performance is the same in my tests. :)

**Comment by liveforeverx** [comment]
On Mariadb I've get mostly the same results for myslqex and mariaex:

```
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mariaex
Running 10s test @ http://localhost:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.40s   437.61ms   1.63s    87.30%
    Req/Sec     3.70      5.62    19.00     80.95%
  773 requests in 10.01s, 274.78KB read
  Non-2xx or 3xx responses: 773
Requests/sec:     77.24
Transfer/sec:     27.46KB
[Air] ~/personal/elixir_database_driver_benchmark % ./wrk -c 100 -d 10 -t 20 http://localhost:8800/mysqlex
zsh: no such file or directory: ./wrk
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mysqlex
Running 10s test @ http://localhost:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.62s   689.73ms   2.50s    52.54%
    Req/Sec     3.58      3.66    17.00     87.01%
  741 requests in 10.02s, 251.10KB read
  Non-2xx or 3xx responses: 741
Requests/sec:     73.99
Transfer/sec:     25.07KB
```

I've installing the mysql to trying it out, but I think, that it can be really related to caching, which is the only real difference between 2 adaptors....and it can be the problem of prepare in mysql https://github.com/xerions/mariaex/issues/43

**Comment by tjheeta** [comment]
@josevalim - That's great! Is the same true for Mysql-otp and Mysqlex? 

@liveforeverx - I don't think it's setup correctly. You'll have to comment out the IO.inspect statements and see what is coming from curl. All the responses should be 200.

**Comment by liveforeverx** [comment]
@tjheeta Aha, thanks, sorry, will try again.

**Comment by josevalim** [comment]
@tjheeta I am not sure about MySQL. In any case, this was very important because we are going to force some queries, like BEGIN TRANSACTIONS and so on to use the text protocol as it is much faster. So thanks for all the benchmark work.

**Comment by liveforeverx** [comment]
```
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mariaex
Running 10s test @ http://localhost:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   703.90ms  243.23ms 851.35ms   87.44%
    Req/Sec     7.42      7.59    33.00     83.41%
  1452 requests in 10.01s, 319.04KB read
Requests/sec:    145.12
Transfer/sec:     31.89KB
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mysqlex
Running 10s test @ http://localhost:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.16s   411.33ms   1.41s    84.79%
    Req/Sec     6.21     10.70    45.00     82.10%
  1221 requests in 10.01s, 268.29KB read
Requests/sec:    121.95
Transfer/sec:     26.79KB
```

**Comment by tjheeta** [comment]
@josevalim - Sorry, I total had misread your earlier, I had thought you were comparing ecto performance through postgrex vs epgsql(with extended queries). I'll verify the epgsql vs postgrex numbers. The mysqlex performance difference is probably due to the result parsing in the mapping to convert it to ecto format. 

@liveforeverx - I think there's something strange with your setup. The thing you can see is the latency numbers is 700 ms vs 1 ms. Is the DB not fast enough? Do you have some postgrex results?

**Comment by liveforeverx** [comment]
@tjheeta no, I've commented all other setups out at the moment, the database wasn't warmed, after trying more time, at the moment, I get this:

```
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mariaex
Running 10s test @ http://localhost:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    24.08ms    2.45ms  49.31ms   77.24%
    Req/Sec   209.97     22.30   277.00     72.29%
  41558 requests in 10.00s, 8.92MB read
Requests/sec:   4154.53
Transfer/sec:      0.89MB
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 10 -t 20 http://localhost:8800/mysqlex
Running 10s test @ http://localhost:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.43ms    4.57ms  79.55ms   91.89%
    Req/Sec   265.97     39.38   365.00     75.83%
  52528 requests in 10.00s, 11.27MB read
Requests/sec:   5252.73
Transfer/sec:      1.13MB
```

Seems, still be slow...

**Comment by liveforeverx** [comment]
@tjheeta I'll implement quick test improvement, will you be available for testing it on you setup too?

**Comment by tjheeta** [comment]
Sure can do. Also, what is the database that you are testing against? 

vagrant@test:~$ dpkg -l|grep mysql-server
ii  mysql-server                    5.5.43-0ubuntu0.14.04.1        all          MySQL database server (metapackage depending on the latest version)

**Comment by liveforeverx** [comment]
MySQL: `Server version: 5.6.21 Homebrew`

**Comment by liveforeverx** [comment]
@tjheeta ok, can you test branch "cached" (I've setuped it as: `{:mariaex, github: "xerions/mariaex", branch: "cached", override: true}`) ?

**Comment by liveforeverx** [comment]
@tjheeta on my notebook, mariaex now constantly performs better than `mysqlex`:

```
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 20 -t 20 http://localhost:8800/mysqlex
Running 20s test @ http://localhost:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.20ms    7.40ms 137.41ms   98.12%
    Req/Sec   270.24     36.75   365.00     78.59%
  106758 requests in 20.00s, 22.90MB read
Requests/sec:   5337.43
Transfer/sec:      1.15MB
[Air] ~/personal/elixir_database_driver_benchmark % wrk -c 100 -d 20 -t 20 http://localhost:8800/mariaex
Running 20s test @ http://localhost:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.56ms    2.48ms  53.49ms   87.27%
    Req/Sec   307.77     36.93   428.00     71.95%
  121458 requests in 20.00s, 26.06MB read
Requests/sec:   6073.48
Transfer/sec:      1.30MB
```

But, I'll setup tests on amazon instance in next days, if something wrong with my database setup.

**Comment by tjheeta** [comment]
~~~
./wrk -c 100 -d 10 -t 20 http://localhost:8800/mariaex
Running 10s test @ http://localhost:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    42.60ms   12.41ms 103.49ms   66.63%
    Req/Sec   117.47     32.52   210.00     60.20%
  23479 requests in 10.04s, 5.04MB read
Requests/sec:   2337.98
Transfer/sec:    513.62KB

./wrk -c 100 -d 10 -t 20 http://localhost:8800/mysqlex
Running 10s test @ http://localhost:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.07ms    5.33ms 101.60ms   96.36%
    Req/Sec   468.81     64.68   828.00     87.51%
  93574 requests in 10.10s, 20.07MB read
Requests/sec:   9265.44
Transfer/sec:      1.99MB
~~~

The performance has improved quite a bit on the new branch, but I think it was giving me the wrong results on the query. I did an IO.inspect before running the benchmark and I got this:
~~~
%Mysqlex.Result{columns: ["id", "name"], command: :select, last_insert_id: nil,
 num_rows: 2, rows: [{1, "something"}, {2, "something"}]}
%Mariaex.Result{columns: ["id", "name"], command: :select, last_insert_id: nil,
 num_rows: 4920,
...
~~~
I restarted the application and it gave me the correct result. Now it's been a long day and I'm pretty sure I didn't delete anything from the db. I would have checked the binary logs if I had them turned on, but I don't. Something to watch out for if it happens again. 

If we can't figure out what's going on sooner than later, I'll see if I can setup a CI for these performance metrics.

**Comment by liveforeverx** [comment]
@tjheeta was small bug in cached version, I've fixed it. 

I've tested now on 2 CPUs digital ocean machine, and get at the moment not so much difference as in your case(twice better, as on your setup). Is there a way, what I need to do to reproduce it, as it is on your machine?

```
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 10 -t 20 http://127.0.0.1:8800/mariaex
Running 10s test @ http://127.0.0.1:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.85ms    4.19ms  67.50ms   82.18%
    Req/Sec   241.04     42.38   750.00     82.25%
  48210 requests in 10.10s, 10.34MB read
Requests/sec:   4773.00
Transfer/sec:      1.02MB
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 10 -t 20 http://127.0.0.1:8800/mysqlex
Running 10s test @ http://127.0.0.1:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.34ms    3.48ms  56.69ms   80.09%
    Req/Sec   259.66     37.53   550.00     74.14%
  52056 requests in 10.10s, 11.17MB read
Requests/sec:   5154.40
Transfer/sec:      1.11MB
```

**Comment by liveforeverx** [comment]
After removing String.strip (which eats 9% of time)
```
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 10 -t 20 http://127.0.0.1:8800/mariaex
Running 10s test @ http://127.0.0.1:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.09ms    3.53ms  77.73ms   87.87%
    Req/Sec   263.66     29.02   330.00     79.09%
  52667 requests in 10.10s, 11.30MB read
Requests/sec:   5215.33
Transfer/sec:      1.12MB
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 10 -t 20 http://127.0.0.1:8800/mysqlex
Running 10s test @ http://127.0.0.1:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.46ms    3.66ms  80.87ms   87.81%
    Req/Sec   258.57     30.61   323.00     73.24%
  51626 requests in 10.10s, 11.08MB read
Requests/sec:   5113.03
Transfer/sec:      1.10MB
```

I've get the same results, will profile more.

**Comment by josevalim** [comment]
I have proposed to @liveforeverx the driver should not be sanitizing the input. In any case, String.rstrip was horribly inefficient as it would always traverse the whole string. I have improved it in Elixir master to be no longer linear and it is now 25x faster for a string with 100 bytes.

**Comment by liveforeverx** [comment]
With all changes in cached branch, I get at the moment constantly 3-7% better performance as mysqlex on my digital ocean instance. I will finalize the changes this week.

**Comment by josevalim** [comment]
@tjheeta Ah, no, I was comparing epgsql directly with postgrex, both behind a pool. :)

Ecto is indeed going to be slower if you are writing Ecto queries as we need to translate them to strings, regardless of the adapter. However, I was actually pleasantly surprised it is only 10-15% slower, as it gives a lot of flexibility when composing queries. And that is because we are still not caching query generation, which, according to my early benchmarks, made Ecto queries 10% faster.

**Comment by liveforeverx** [comment]
@josevalim, @tjheeta the issue for prepared statements slowdown seems to be on mysql side. Sometimes waiting between prepare sent and prepare_ok was received is 40 ms without reason, which were not reproducible on mariadb, it is something on mysql side, what will be fixed with query caching.

**Comment by tjheeta** [comment]
@josevalim - Ecto is definitely pleasantly surprising. :) Hopefully, the raw performance can get to within 5% on simple selects. 

@liveforeverx - that makes sense with what I was seeing earlier. It kind of scares me that there's a difference between mysql and maria at this low level. What is the mysql/maria version you used on Digitalocean?

**Comment by liveforeverx** [comment]
@tjheeta I've used the same mysql version on digital ocean( "Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu)" ) as you have. Extra to test, that I have the same performance with mariaex as mysqlex.

**Comment by tjheeta** [comment]
It's working for me now. We'll need to test concurrent inserts and selects to make sure the cached statements are returning correctly. 

./wrk -c 100 -d 10 -t 20 http://localhost:8801/mariaex
Running 10s test @ http://localhost:8801/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.12ms    2.88ms  50.59ms   83.63%
    Req/Sec   415.45     51.31   777.00     67.68%
  82987 requests in 10.10s, 17.80MB read
Requests/sec:   8218.11
Transfer/sec:      1.76MB

./wrk -c 100 -d 10 -t 20 http://localhost:8801/mysqlex
Running 10s test @ http://localhost:8801/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.74ms    3.27ms  64.12ms   91.55%
    Req/Sec   431.54     48.80   555.00     80.60%
  86170 requests in 10.05s, 18.49MB read
Requests/sec:   8576.65
Transfer/sec:      1.84MB

**Comment by liveforeverx** [comment]
@tjheeta Thanks for confirmation!

Can you try to run both with -d 30 and post the results too??

**Comment by tjheeta** [comment]
./wrk -c 100 -d 30 -t 20 http://localhost:8801/mysqlex
Running 30s test @ http://localhost:8801/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.09ms    3.04ms  82.75ms   92.11%
    Req/Sec   456.72     50.92   666.00     75.87%
  273515 requests in 30.10s, 58.68MB read
Requests/sec:   9087.02
Transfer/sec:      1.95MB

./wrk -c 100 -d 30 -t 20 http://localhost:8801/mariaex
Running 30s test @ http://localhost:8801/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.77ms    3.83ms  81.41ms   91.11%
    Req/Sec   432.67     76.02   550.00     80.47%
  258602 requests in 30.10s, 55.48MB read
Requests/sec:   8591.62
Transfer/sec:      1.84MB

**Comment by liveforeverx** [comment]
@tjheeta is the last run with `MIX_ENV=prod` ? I'll try to figure out, why it is slower in your setup.

**Comment by liveforeverx** [comment]
I can reproduce it slower, only in cases, if I didn't start with `MIX_ENV=prod` :

```
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 30 -t 20 http://127.0.0.1:8800/mariaex
Running 30s test @ http://127.0.0.1:8800/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.75ms    2.51ms  62.49ms   75.33%
    Req/Sec   254.18     23.02   313.00     67.13%
  152026 requests in 30.04s, 32.61MB read
Requests/sec:   5060.85
Transfer/sec:      1.09MB
root@test:~/dev/elixir_database_driver_benchmark# wrk -c 100 -d 30 -t 20 http://127.0.0.1:8800/mysqlex
Running 30s test @ http://127.0.0.1:8800/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.18ms    2.74ms  46.00ms   75.01%
    Req/Sec   261.59     27.90   330.00     62.05%
  156436 requests in 30.04s, 33.56MB read
Requests/sec:   5208.04
Transfer/sec:      1.12MB
```

**Comment by tjheeta** [comment]
Yup, I didn't start it with prod, but it's a laptop, so I'm not expecting the runs to be too consistent.

~~~
MIX_ENV=prod iex -S mix
./wrk -c 100 -d 30 -t 20 http://localhost:8802/mariaex
Running 30s test @ http://localhost:8802/mariaex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.72ms    5.14ms 124.21ms   93.85%
    Req/Sec   439.11     71.65     0.88k    74.44%
  262367 requests in 30.10s, 56.29MB read
Requests/sec:   8717.96
Transfer/sec:      1.87MB
./wrk -c 100 -d 30 -t 20 http://localhost:8802/mysqlex
Running 30s test @ http://localhost:8802/mysqlex
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.41ms    4.74ms 158.29ms   95.50%
    Req/Sec   450.21     57.39   690.00     77.56%
  268974 requests in 30.09s, 57.70MB read
Requests/sec:   8938.29
Transfer/sec:      1.92MB

~~~

**Comment by josevalim** [comment]
@tjheeta i have tried using mysqlex but it fails some of the integration tests (from the top of my mind, the ones that require Decimal). Are the current improvements good enough for you or would you still like to plug your own adapter? If so, I can merge my changes in, but you would need at least Decimal support for a passing suite.

**Comment by tjheeta** [comment]
OK, I need to learn how to use an irc client. 

The speed improvements are good. I just want to make sure there are no inadvertent bugs under load, I dislike finding these things out in a production environment. I don't suppose there is already a test suite that does what I want to do? 

I think the plugging functionality may come in handy if it's not too much trouble.

**Comment by josevalim** [comment]
@tjheeta I am closing this for now as I could not find out a straight-forward way to support multiple drivers. However, you can always create your own driver that delegates the query generation and so on to the Mariaex one. Thanks for bringing this up, all drivers are now faster because of this discussion!
